resolver: lts-7.3
flags: {}

packages:
- truth-backend
- truth-scraper

extra-deps:
- conduit-extra-1.1.15
- esqueleto-2.4.3
- logging-effect-1.1.0
- persistent-2.2.4.1
- persistent-sqlite-2.2.1
- persistent-template-2.1.8.1
- protolude-0.1.10
- servant-quickcheck-0.0.2.1
- wai-extra-3.0.19
- warp-3.2.9
